-- Leasing KM Tracker (PUBLIC MODE)
-- Creates a public table for readings. WARNING: This is intentionally public.

create table if not exists public.readings (
  id bigint generated by default as identity primary key,
  date date not null,
  odometer_km integer not null check (odometer_km >= 0),
  created_at timestamptz not null default now()
);

-- Optional helpful index
create index if not exists readings_date_idx on public.readings(date);

-- PUBLIC ACCESS (not recommended for sensitive data)
alter table public.readings enable row level security;

-- Allow anyone (anon) to read
drop policy if exists "public read" on public.readings;
create policy "public read" on public.readings
  for select
  to public
  using (true);

-- Allow anyone (anon) to insert
drop policy if exists "public insert" on public.readings;
create policy "public insert" on public.readings
  for insert
  to public
  with check (true);

-- Allow anyone (anon) to delete (so family can correct mistakes). If you want safer mode, remove this.
drop policy if exists "public delete" on public.readings;
create policy "public delete" on public.readings
  for delete
  to public
  using (true);
